# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

all:
  .settings:
    etag: true

prod:
  .settings:
    no_script_name:         true
    cache:                  true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

cache:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  true
    no_script_name:         false
    etag:                   false
    logging_enabled:        false

all:
  .settings:
    default_culture:        pl
    use_process_cache:      on
    # Form security secret (CSRF protection)
    csrf_secret:            0fa754e1028d65a474f0b3d361a8b9561ade9f8a

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_RAW #ESC_ENTITIES

    # Enable the database manager
    use_database:           true

    i18n:                   true       # Enable interface translation. Set to off if your application should not be translated.
    charset:                utf-8
    standard_helpers:       [Partial, Cache, JavascriptBase, I18N]
    check_lock:             true
    compressed:             true

  .actions:
    error_404_module:       error   # To be called when a 404 error is raised
    error_404_action:       error404  # Or when the requested URL doesn't match any route
